project_id = "lndyurrvcblxnkjprdwr"

[functions.analyze-bug-report]
verify_jwt = true

[functions.analyze-feature-request]
verify_jwt = true

[functions.request-bug-satisfaction]
verify_jwt = true

[functions.notify-bug-status-change]
verify_jwt = false

[functions.accept-invitation]
verify_jwt = false

[functions.generate-daily-quote]
verify_jwt = false

[functions.generate-metric-info]
verify_jwt = false

[functions.send-team-invite]
verify_jwt = true

[functions.generate-vendor-report]
verify_jwt = true

[functions.generate-listing-description]
verify_jwt = true

[functions.coaches-corner-chat]
verify_jwt = false

[functions.ai-task-suggestions]
verify_jwt = true

[functions.notify-team-transaction]
verify_jwt = false

[functions.notes-ai]
verify_jwt = true

[functions.invite-user]
verify_jwt = true

[functions.repair-user]
verify_jwt = true

[functions.resend-invitation]
verify_jwt = true

[functions.change-user-role]
verify_jwt = true

[functions.suspend-user]
verify_jwt = true

[functions.delete-user]
verify_jwt = true

[functions.send-orphan-repair-email]
verify_jwt = true

[functions.create-admin-user]
verify_jwt = false
